config/routes.rb
Rails.application.routes.draw do
  root "home_page#index"
  resources :vacancies, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  SOURCES = {
    "frontendbr/vagas" => "Front-End BR - Vagas",
    "backend-br/vagas" => "Back-End BR - Vagas",
    "react-brasil/vagas" => "React BR - Vagas",
    "qa-brasil/vagas" => "QA BR - Vagas"
  }.freeze

  searchkick(
    batch_size: 10_000,
    word_start: [:name]
  )

  validates :external_id, :external_source, :url, :title, :user_login, :user_avatar_url, :user_profile_url, :labels, :body, presence: true

  def tags
    parsed_tag = JSON.parse(labels)
    parsed_tag.map do |sub_array|
      sub_array.to_h
    end
  end

  def search_data
    attributes.merge(
      labels: tags.map { |l| l["name"] }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  include Pagy::Backend

  def index
    @vacancies = VacancySearchPresenter.new(query: params[:q], options: search_params).search
    @pagy = Pagy.new_from_searchkick(@vacancies)
    @start_date = params[:start_date]
    @end_date = params[:end_date]
  end

  def show
  end

  private

  def search_params
    params.permit(:q, :page, :user, :label, :source)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def markdown(text)
    MarkdownRenderer.render(text).html_safe
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/home_page/index.html.erb
<div class="home-page">
  <div class="container">
    <div class="row height d-flex justify-content-center align-items-center">
      <div class="col-md-6">
        <h1 class=" poppins">VAGAS DE TI</h1>
        <%= form_with url: vacancies_path, method: :get, local:true, data: { turbo: "false" } do |form| %>
          <div class="input-group">
            <%= form.text_field :q, class: "form-control border-0", placeholder: "Pesquise sua vaga", value: params[:q] %>
            <span class="input-group-btn">
              <button class="shadow-none border-0 btn btn-light mb-0 rounded-0 rounded-end" type="submit"><i class="fa fa-search"></i></button>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagas de TI</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_filters.html.erb
<%
  parameters = params.except(:controller, :action, :page).to_unsafe_h
%>
<h3 class="grid-title"><%= link_to 'VAGAS DE TI', root_path, class:'black' %></h3>
<hr>
<!-- BEGIN FILTER BY DATE -->
<h5>Data:</h5>
<%= form_with url: vacancies_path, method: :get, local: true, id: 'dateForm', data: { turbo: "false" } do |form| %>
  De
  <div class="input-group date form_date">
    <input type="date" name="start_date" class="form-control" id="startDateInput">
  </div>
  Para
  <div class="input-group date form_date">
    <input type="date" name="end_date"class="form-control" id="endDateInput">
  </div>
<% end %>
<!-- END FILTER BY DATE -->
<!-- BEGIN FILTER BY CATEGORY -->
<h5 class="pt-3">Categoria:</h5>
<ul class="list-unstyled">
  <% vacancies.aggs['labels']['buckets'].sort_by{|label| label['doc_count'] }.reverse.each do |label| %>
    <li>
      <%= link_to "#{label['key']} (#{label['doc_count']})", vacancies_path(parameters.merge(label: label['key'])) %>
    </li>
  <% end %>
</ul>
<!-- END FILTER BY CATEGORY -->

app/views/partials/_footer.html.erb
<footer class="content-footer footer bg-footer-theme">
   <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
      <div class="mb-2 mb-md-0">
         Vagas de TI - <%= Date.current.year %>. Feito com ❤️ em Ruby on Rails
      </div>
      <div class="d-none d-lg-inline-block">
         <a href="#!" class="footer-link me-4" target="_blank">Sobre</a>
      </div>
   </div>
</footer>
<div class="content-backdrop fade"></div>
</div>

app/views/partials/_menu.html.erb
<%
  parameters = params.except(:controller, :action, :page).to_unsafe_h
%>
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <div class="app-brand pt-3">
    <a href="/" class="app-brand-link">
      <span class="app-brand-logo demo">
      </span>
      <span class="app-brand-text demo menu-text fw-bold ms-2">VAGAS DE TI</span>
    </a>
    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="fa-solid fa-circle-chevron-left back-icon"></i>
    </a>
  </div>
  <div class="menu-inner-shadow"></div>
  <ul class="menu-inner py-5">
    <li class="menu-item">
      <div class="px-4">
        <div class="pb-3">
          <i class="menu-icon fa-solid fa-calendar-days"></i>
          Data:
        </div>
        <%= form_with url: vacancies_path, method: :get, local: true, id: 'dateForm', data: { turbo: "false" } do |form| %>
          De
          <div class="input-group date form_date">
            <input type="date" name="start_date" class="form-control" id="startDateInput">
          </div>
          <div class="pt-2">Para</div>
          <div class="input-group date form_date">
            <input type="date" name="end_date"class="form-control" id="endDateInput">
          </div>
        <% end %>
      </div>
    </li>
    <li class="menu-item pt-3 open" style="">
      <a href="javascript:void(0);" class="menu-link menu-toggle">
        <i class=" menu-icon fa-solid fa-tags"></i>
        <div class="margin-category">Categorias</div>
      </a>
      <ul class="menu-sub">
        <% @vacancies.aggs['labels']['buckets'].sort_by{|label| label['doc_count'] }.reverse.each do |label| %>
          <li class="menu-item">
            <%= link_to vacancies_path(parameters.merge(label: label['key'])), class: "menu-link" do %>
              <div><%= label['key'] %></div>
              <div class="badge bg-label-primary fs-tiny rounded-pill ms-auto"><%= label['doc_count'] %></div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
</aside>

app/views/partials/_results.html.erb
<!-- Layout container -->
<div class="layout-page">
<!-- Navbar -->
<nav
   class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
   <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0   d-xl-none ">
      <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
         <i class="fa-solid fa-bars"></i>
      </a>
   </div>
   <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
      <!-- Search -->
      <%= form_with url: vacancies_path, method: :get, local:true, data: { turbo: "false" } do |form| %>
         <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center">
               <i class="fa-solid fa-magnifying-glass"></i>
               <%= form.text_field :q, class: "form-control border-0 shadow-none ps-1 ps-sm-2", placeholder: "Pesquise sua vaga", value: params[:q] %>
            </div>
         </div>
      <% end %>
      <!-- /Search -->
   </div>
</nav>
<!-- / Navbar -->
<!-- Content wrapper -->
<div class="content-wrapper">
   <!-- Content -->
   <div class="container-xxl flex-grow-1 container-p-y">
      <h4 class="py-3 mb-4">
         <% if params[:q].present? %>
         <span class="text-muted fw-light">Exibindo resultados para a pesquisa /</span><%= params[:q] %>
         <% end %>
         <% if @start_date.present? && @end_date.present? %>
         <span class="text-muted fw-light">Exibindo vagas entre / <%= Date.parse(@start_date).strftime('%d/%m/%Y') %> e <%= Date.parse(@end_date).strftime('%d/%m/%Y') %>
         <% end %>
      </h4>
      <!-- Basic Bootstrap Table -->
      <div class="card">
         <h5 class="card-header">Resultados</h5>
         <div class="table-responsive">
            <table class="table">
               <tbody class="table-border-bottom-0">
                  <% @vacancies.each do |vacancy| %>
                  <tr>
                     <td class="product">
                        <h4><a href="<%= vacancy.url %>" target="_blank"><%= vacancy.title %></a></h4>
                        <div class="">
                           <%= markdown(truncate(vacancy.body, length: 300, omission: '... ')) %>
                        </div>
                        <div>
                           <% vacancy.tags.each do |tag| %>
                           <%= link_to vacancies_path(label: tag['name']), class: "text-decoration-none" do %>
                           <span class="badge badge-pill " style="background-color:#<%= tag.to_h['color']%>"><%= tag.to_h['name']%></span>
                           <% end %>
                           <% end%>
                        </div>
                     </td>
                  </tr>
                  <% end%>
               </tbody>
            </table>
            <hr>
            <div class="m-2">
               <%== pagy_bootstrap_nav(@pagy) %>
            </div>
         </div>
      </div>
      <!--/ Basic Bootstrap Table -->
   </div>
   <!-- / Content -->
   <%= render("partials/footer") %>
</div>

app/views/vacancies/index.html.erb
<div class="layout-wrapper layout-content-navbar">
  <div class="layout-container">
    <%= render("partials/menu") %>
    <%= render("partials/results") %>
  </div>
</div>